package com.example.devov.historyapp.utils.dao.autoGenerate;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "NEWS".
 */
@Entity
public class News {

    @Id
    private Long id;

    @Unique
    private String type;
    private String document;
    @Generated(hash = 1742191919)
    public News(Long id, String type, String document) {
        this.id = id;
        this.type = type;
        this.document = document;
    }
    @Generated(hash = 1579685679)
    public News() {
    }
    public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    public void setType(String type) {
        this.type = type;
    }
    public String getDocument() {
        return this.document;
    }
    public void setDocument(String document) {
        this.document = document;
    }


}
